### ISSUE TITLE
Demo does not work on OS X, Safari

### ISSUE THREAD

**Issue by Sohojoe** [zabirauf/icsharp#21]
user can not edit text
user can not ctrl-return to run line

repro steps:

1. click readme->demo
2. nbViewer page loads
3. click on In [1]: int someInteger = 123456; 

Link:

 http://nbviewer.ipython.org/urls/gist.githubusercontent.com/zabirauf/a0d4aa22b383afaa1e23/raw/65e539dc98b2cf3e38cc26faf3575e50f4ac9108/iCSharp%20Sample.ipynb

**Comment by denfromufa** [comment]
how did you install icsharp on osx?

**Comment by Sohojoe** [comment]
doh - i had assumed it was a demo running on hosted server - i will re-read the docs re getting it set up
