### ISSUE TITLE
Unable to build

### ISSUE THREAD

**Issue by gordonwatts** [zabirauf/icsharp#28]
After doing a git clone, I do a build in Visual Studio 2015 update 3, and it fails to build. The error is that many of the references to packages in the build files (the csproj files) seem to assume the project is in the top level directory.

For example:

      <Import Project="..\..\packages\StyleCop.MSBuild.4.7.49.0\build\StyleCop.MSBuild.Targets" Condition="Exists('..\..\packages\StyleCop.MSBuild.4.7.49.0\build\StyleCop.MSBuild.Targets')" />

causes a failure, but changing that line to:

      <Import Project="$(SolutionDir)\packages\StyleCop.MSBuild.4.7.49.0\build\StyleCop.MSBuild.Targets" Condition="Exists('$(SolutionDir)\packages\StyleCop.MSBuild.4.7.49.0\build\StyleCop.MSBuild.Targets')" />

seems to fix it.

I think this is because you are pulling down ScriptCS as a git sub-project (but I'm not 100% sure if this is the reason)... and since they have installed packages in ScriptCS it isn't picking up yours correctly since it is in the wrong place.

**Comment by gordonwatts** [comment]
Work around. Open the ScriptCS solution file in the Engine directory, open nuget mangement, and do a restore packges. Close the solution, and in the iCSharp do the build. Now it will work fine.

**Comment by ChandraSannamuri** [comment]
i am also facing the same issue in Mac, while trying to build in terminal with  following command

(base) $ bash ./build.sh brew
+ mozroots --import --sync --quiet
./build.sh: line 7: mozroots: command not found
