### ISSUE TITLE
Built failed in VS2017

### ISSUE THREAD

**Issue by wanglongqi** [zabirauf/icsharp#35]
I followed the instruction on [https://github.com/zabirauf/icsharp/wiki/Installation](https://github.com/zabirauf/icsharp/wiki/Installation) to install this package. The package cannot be built in VS2017.

Following are the output in the process:

> 
> C:\Download>git clone --recursive https://github.com/zabirauf/icsharp
> Cloning into 'icsharp'...
> remote: Counting objects: 367, done.
> remote: Total 367 (delta 0), reused 0 (delta 0), pack-reused 367
> Receiving objects: 100% (367/367), 1.78 MiB | 679.00 KiB/s, done.
> Resolving deltas: 100% (211/211), done.
> Submodule 'Engine' (https://github.com/scriptcs/scriptcs.git) registered for path 'Engine'
> Cloning into '/c/Download/icsharp/Engine'...
> remote: Counting objects: 14014, done.
> remote: Compressing objects: 100% (4/4), done.
> remote: Total 14014 (delta 0), reused 0 (delta 0), pack-reused 14010
> Receiving objects: 100% (14014/14014), 22.35 MiB | 1.01 MiB/s, done.
> Resolving deltas: 100% (9529/9529), done.
> Submodule path 'Engine': checked out 'ceb8443df52ae872a125832a3d89a13b00cd2b54'

Build solution:

> Severity	Code	Description	Project	File	Line	Suppression State
> Error		This project references NuGet package(s) that are missing on this computer. Use NuGet Package Restore to download them.  For more information, see http://go.microsoft.com/fwlink/?LinkID=322105. The missing file is ..\..\packages\StyleCop.MSBuild.4.7.50.0\build\StyleCop.MSBuild.Targets.	ScriptCs (ScriptCS\ScriptCs)	C:\Download\icsharp\Engine\src\ScriptCs\ScriptCs.csproj	178	
> Error		This project references NuGet package(s) that are missing on this computer. Enable NuGet Package Restore to download them.  For more information, see http://go.microsoft.com/fwlink/?LinkID=322105. The missing file is ..\..\packages\StyleCop.MSBuild.4.7.49.0\build\StyleCop.MSBuild.Targets.	ScriptCs.Contracts	C:\Download\icsharp\Engine\src\ScriptCs.Contracts\ScriptCs.Contracts.csproj	129	
> Error		This project references NuGet package(s) that are missing on this computer. Enable NuGet Package Restore to download them.  For more information, see http://go.microsoft.com/fwlink/?LinkID=322105. The missing file is ..\..\packages\StyleCop.MSBuild.4.7.49.0\build\StyleCop.MSBuild.Targets.	ScriptCs.Core	C:\Download\icsharp\Engine\src\ScriptCs.Core\ScriptCs.Core.csproj	124	
> Error		This project references NuGet package(s) that are missing on this computer. Enable NuGet Package Restore to download them.  For more information, see http://go.microsoft.com/fwlink/?LinkID=322105. The missing file is ..\..\packages\StyleCop.MSBuild.4.7.49.0\build\StyleCop.MSBuild.Targets.	ScriptCs.Hosting	C:\Download\icsharp\Engine\src\ScriptCs.Hosting\ScriptCs.Hosting.csproj	130	
> 

Do a `nuget restore`:

> All packages are already installed and there is nothing to restore.
> Time Elapsed: 00:00:00.0458248
> ========== Finished ==========
> 

What should I do from here?

**Comment by zabirauf** [comment]
@wanglongqi Were you able to solve the problem?

**Comment by wanglongqi** [comment]
@zabirauf Yes, I built the engine first. Then the project can be built.
