### ISSUE TITLE
Console.WriteLine does not print output in the notebook

### ISSUE THREAD

**Issue by awb99** [zabirauf/icsharp#4]
I think you can register for Console Printouts via Trace.Listener.Add.
Here is a snipped that use to display a virtual console:

```
    #region  HelperClass TConsoleTraceListener
    public class TConsoleTraceListener : TraceListener
    {
        #region Variables
        TConsole _parent;
        #endregion

        #region Constructor
        public TConsoleTraceListener (TConsole parent)
        {
            _parent = parent;
            //Debug.Listeners.Clear ();
            //Debug.Listeners.Add (this);
            //Trace.Listeners.Clear ();
            Trace.Listeners.Add (this);
        }
        #endregion

        #region TraceListener Overrides
        override public void Write(string message) 
        {
            try
            {
                _parent.WriteLine (message);
            }
            catch (Exception ex)
            {
                ;
                Console.Write ("Ex="+ex.Message );
            }
        }
        override public void WriteLine(string message) 
        {     
            try
            {
                _parent.WriteLine (message);
            }
            catch (Exception ex)
            {
                ;
                Console.Write ("Ex="+ex.Message );
            }
        }
        #endregion
    }
    #endregion
```

**Comment by denfromufa** [comment]
@awb99 did you get icsharp working with ipython/jupyter? if yes, which versions?

**Comment by awb99** [comment]
I did not. But I am still looking into it. I love IPhython, and I cannot understand why there seems to be almost nobody out there who wants to use c# in Jupyter.

**Comment by denfromufa** [comment]
I started a discussion here: https://groups.google.com/forum/#!topic/jupyter/VsCF9xHNp6Y

**Comment by zabirauf** [comment]
@awb99 Thanks for opening the issue. I will first look into making it work with the update ipython. Feel free to send a pull request if you figure out the issue and have a fix.

**Comment by awb99** [comment]
I think one has two problems to solve: 1. running a C# shell in a REPL mode in a linux terminal. (I think I could get this done). This mainly defines the syntax and can print out the status of variables to Console.  2. integration with Jupyter. For this one needs to study more the interface that Jupyter requieres, and then implement it... Both tasks should be doable. And both tasks will have lots implementation issues...

**Comment by awb99** [comment]
ICSharp seems to implement a ZMQ messages that are sent via JSON. 
What I dont understand why building it needs Python.
Should be a pure .net application...

**Comment by denfromufa** [comment]
@awb99 I built ICSHARP using VS 2015 with GitHub extension, just cloned the repository. I do not think that Python is required for build. I did have to make some changes (add alias for MonoCSharp and replace deprecated calls) and install 3rd party packages using nuget console in VS 2015.
But the fun part is then launching jupyter/ipython notebook. Did you succeed in doing so?

**Comment by awb99** [comment]
Ahh.. I think now I understand: The notes in the README regarding INSTALLATION are ONLY relevant AFTER the solution has been compiled!   Monodevelop has problems in getting the ScriptCS dependencies. It might be because it does not trust the NuGet links?  I am usting the Manjaro Linux which is a rolling distribution based on ARCH; so I believe I have the latest versions of all components. I wil try to compile ScriptCs separately, and then in iICSharp just reference the dlls. I will revert shortly.

**Comment by zabirauf** [comment]
To compile

1- Clone the project (recursive so that submodule is cloned as well)
2- Open the solution
3- Right click on solution and select manage dependencies
  1- Select option to restore nuget packages
4- Open CMD and navigate to Engine and run `build.cmd`
5- Compile icsharp

This will build the icsharp

**Comment by zabirauf** [comment]
@awb99 as @denfromufa stated python is not required, icsharp is a pure c# project. The instruction in README is to run icsharp as ipython kernel.

**Comment by awb99** [comment]
Thank you so much guys!! With clone recursively with ./Engine/build.sh I now managed to build the engine, and the project now builds with MonoDevelop! So will see if I manage to run it in Jupyter..

**Comment by awb99** [comment]
All dlls are compiled correctyly now... So now it is to integrate icsharp with Jupyter.
Seems that Chocholatey is pure windows package manager. So I am going to investigate
how to integrate engines with Jupyter...

**Comment by denfromufa** [comment]
@awb99 looks like ICSHARP is not compatible with latest Jupyter protocol, see the errors I'm getting here:
https://github.com/zabirauf/icsharp/issues/5

**Comment by awb99** [comment]
Ok. So the only thing to find out for me then is, which of the ICsharp dlls I need to copy where, so that they work under linux. The cholcolatey config only works on Windows I believe.

**Comment by awb99** [comment]
I am working on the linux settings file for icsharp. I think witht he Chocolatey install, you just amend a ipython settings file. What I havent figured out, is how to call the binary file. In mono you need to call the app mono icsharp.exe   Just calling icsharp.exe will not get it done.

**Comment by denfromufa** [comment]
I  think we should build conda/wheel package for cross-platform installation

**Comment by awb99** [comment]
I will first try to get it to work... I guess the last version of IPython that should work with icsharp is 2.4.1
I cannot find this verion in debian or arch packets, so I will try to build this version of IPython and study the sources; perhaps I find out how the kernel expects the app parameters.

**Comment by awb99** [comment]
I posted on the Jupyter forum.. I need to know if I can pass paramete, as this is how mono apps are called on Unix...

**Comment by awb99** [comment]
I am not sure if going with IPython 2.4.1 is the way to go. It is reasonable simple to find this version, and to compile it. However, to get the old version of PyZMQ to get running is not so easy. The 
sudo pip install pyzmq==2.1.11   fails...  I believe I ned to go to an other version of gcc too...
Ahhhh

**Comment by denfromufa** [comment]
According to Matthias ipython 3 should have adapters for kernels from
ipython 2

**Comment by awb99** [comment]
I think it is not only Console.WriteLine that does not work, but also undefined Variables.
Strangely EXCEPTIONS do work.
On Mono I can see the Console.WriteLine Output in the shell, so redirecting this should be easy.
See  the attached screenshot

Not sure if this error appears also on windows or not:
[W 15:24:10.431 NotebookApp] Timeout waiting for kernel_info reply from 00c51217-4953-4e1e-ba44-c902ded0e81f




![behavior on mono](https://cloud.githubusercontent.com/assets/10854682/9837381/20315596-5a2c-11e5-8425-ea0a320c9d65.png)
