### ISSUE TITLE
Suggestion: Change iCSharp.Kernel.exe.config

### ISSUE THREAD

**Issue by awb99** [zabirauf/icsharp#6]
Additional dlls will be able to be loaded into iCSharp.Kernel.
The location of such dlls will have to be either GAC or the directory in which
iCSharp.Kernel is located.
Dotnet offers a simple way to load dlls from subdirectories. Say we have
a huge library in the subdirectory customDir1 and customDir2 then the
App.Config needs to be appended (after the startup node is closed)
with the following:

```
  <runtime>
  <assemblyBinding xmlns="urn:schemas-microsoft-com:asm.v1">
  <probing privatePath="customDir1;customDir2" />
  </assemblyBinding>
  <trust level="Full" legacyCasModel="true" />
  </runtime>
```

Why do I suggest this? A more clear separation of the kernel from custom
third party dlls.

Note:  I dont understand why the xml markup does not show above. It is there.

**Comment by gwenzek** [comment]
What are the modifications you're suggesting ?

To quote xml try triple ` followed by 'xml' like in [this SO question](http://stackoverflow.com/questions/9751548/how-do-i-correctly-paste-multi-line-xml-snippet-to-github-wiki-when-using-markdo)
```xml
<myxml>
   <someElement />  
</myxml>
```

**Comment by awb99** [comment]
I am suggesting that iCSharp.Kernel.exe.config gets added the runtime flags; this way one can put custom dlls into customDir1 and customDir2, and they will be able to get loaded in Jupyter/Ipython wth the #load directive.
